const fs = require('fs')
const path = require('path')
const createSidebarData = require('../vdoing/node_utils/getSidebarData')

const docsDir = path.join(__dirname, '..', 'docs')
const outputPath = path.join(docsDir, '.vuepress', 'config', 'sidebar.js')

const sidebarData = createSidebarData(docsDir, true)

const content = `// Auto-generated by utils/generateSidebar.js
// Run "npm run gen:sidebar" after adding, moving, or renaming docs.
module.exports = ${JSON.stringify(sidebarData, null, 2)}
`

fs.writeFileSync(outputPath, content)

console.log(`sidebar cache generated: ${outputPath}`)
